from .parametric_regression_config import ParametricRegressionConfig
from .parametric_regression_config import load_parametric_regression_config

from .gp_regression_config import GPRegressionConfig
from .gp_regression_config import load_gp_regression_config
