# ----- Visuals -----
# Resolution used to display the kernel function. Results in
# kernel_resolution^2 pixels.
kernel_resolution: 400

# Resolution used to display the function space distribution.
# Results in kernel_resolution^2 pixels.
function_space_resolution: 600

# Number of example functions drawn from the Gaussian process.
number_function_samples: 1

# Limits of function space plots.
function_space_xlim: [-5, 5]
function_space_ylim: [-10, 10]

# The vmax value of both plots.
colormap_vmax: 1


# ----- learning -----
# The total number of samples generated.
number_target_samples: 10

# Variance of the Gaussian noise added to the target samples.
target_noise_amount: 1

# Variance of the Gaussian noise assumed by the model.
model_noise_amount: 1

# The time in milliseconds between weight updates. This is the
# minimum time a step will take, the actual time is limited by the
# time it takes to update the weights and to plot the
# distributions.
time_per_learning_step: 300

# Batch size of the dataloader.
samples_per_learning_step: 1
