# ----- Visuals -----
# Resolution used to display the weight distribution. Results in
# kernel_resolution^2 pixels.
weight_space_resolution: 400

# Resolution used to display the function space distribution.
# Results in kernel_resolution^2 pixels.
function_space_resolution: 600

# Limits of weight and function space plots.
weight_space_xlim: [-4, 4]
weight_space_ylim: [-4, 4]
function_space_xlim: [-5, 5]
function_space_ylim: [-15, 15]

# The vmax value of both plots.
colormap_vmax: 1


# ----- Controls -----
# The sensitivity of the mouse wheel when editing the Gaussians
# covariance.
mouse_wheel_sensitivity: 1


# ----- learning -----
# The number of samples from the function to be approximated.
number_target_samples: 100

# Variance of the Gaussian noise added to the target samples.
target_noise_amount: 1

# Variance of the Gaussian noise assumed by the model.
model_noise_amount: 1

# The time in milliseconds between weight updates. This is the
# minimum time a step will take, the actual time is limited by the
# time it takes to update the weights and to plot the
# distributions.
time_per_learning_step: 30

# Batch size of the dataloader.
samples_per_learning_step: 1
